MAX_ROADS = 6
MAX_STRATEGIES=25

# Hidden layers
HIDDEN_DIM = 64
HIDDEN_AMOUNT = 3

# Output (dynamic)
OUTPUT_DIM = MAX_STRATEGIES

# Input (static)
METRICS_PER_ROAD = 4
FLOW_IN_OFFSET = 0
FLOW_OUT_OFFSET = 1
WAIT_DURATION_OFFSET = 2
WAIT_DURATION_CUMULATIVE = 3
INPUT_DIM = METRICS_PER_ROAD * MAX_ROADS
